#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     armstoptouch1,  sensorTouch)
#pragma config(Motor,  motorA,          armpickupmotor1, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          armpickupmotor2, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     blockarm,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     spinnyarm,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

// sets in magical values
#define DIVISOR	2.56
#define ARMDIVISOR 5.12
#define MARGIN 4
// this is for defining an expression to bitmask for the arcade and tank buttons
// button 5 on joystick 1
#define ARCADE	(joystick.joy1_Buttons & 0b00010000)
// button 6 on joystick 1
#define TANK		(joystick.joy1_Buttons & 0b00100000)
// button 5 on joystick 2
#define BUTTONFORPICKUP		(joystick.joy2_Buttons & 0b00010000)
// button 6 on joystick 2
#define BUTTONFORDROPOFF  (joystick.joy2_Buttons & 0b00100000)
//Keep the value a between b and c
#define CONSTRAIN(a, b, c) ( ((a)<(b)) ? (b) : ( ((a)>(c)) ? (c) : (a)) )

//Variable to track arcade and tank modes
bool tank = true;

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	motor[left] = 0;
	motor[right]= 0;
	motor[blockarm] = 0;
  return;
}


void drive()
{
	// this is to retrieve joystick values
	getJoystickSettings(joystick);
	// these switch between arcade and tank mode
	if (ARCADE)
	{
		tank = false;
	}
	if (TANK)
	{
		tank = true;
	}
	// this is tank setting
	if (tank)
	{
		// translating joystick values from 128 to -127 to motor speeds
		float y1 = (float)(joystick.joy1_y1) / DIVISOR;
		float y2 = -(float)(joystick.joy1_y2) / DIVISOR;
		// wheels will be stopped when desired
		y1 = (abs(y1) - MARGIN < MARGIN) ? 0 : y1;
		y2 = (abs(y2) - MARGIN < MARGIN) ? 0 : y2;
		// sets motors
		motor[left] = y1;
		motor[right] = y2;
	}
	// this is arcade mode
	else
	{
		//translating joystick values to motor speeds
		float y = (float)(joystick.joy1_y2) / DIVISOR;
		float x = (float)(joystick.joy1_x2) / DIVISOR;
		// wheels are still when desired
		y = (abs(y) - MARGIN < MARGIN) ? 0 : y;
		x = (abs(x) - MARGIN < MARGIN) ? 0 : x;
		// calculating arcade values
		float left = CONSTRAIN(y + x, -128/DIVISOR, 128/DIVISOR);
		float right = -CONSTRAIN(y - x, -128/DIVISOR, 128/DIVISOR);
		// sets motors
		motor[left] = left;
		motor[right] = right;
	}

}

// this is the arm that picks up the block
void armliftythingy ()
{
	int armmotorspeed = (joystick.joy2_y2) / ARMDIVISOR;
#if 1
	// keeps the arm still when desired
	if (SensorValue[armstoptouch1] == 1)
	{
		if (armmotorspeed > 0)
		{
			motor[blockarm] = armmotorspeed;
		}

		 armmotorspeed = 0;
	}
#endif
	motor[blockarm] = armmotorspeed;
	return;
}


void spinnyarmaction ()
{
	int spinnyarmspeed = (joystick.joy2_y2) / DIVISOR;

	spinnyarmspeed = motor[spinnyarm];
}

void pickup ()
{
	motor[armpickupmotor1] = (BUTTONFORPICKUP);
	motor[armpickupmotor2] = -(BUTTONFORPICKUP);
}

void letgo ()
{
	motor[armpickupmotor1] = -(BUTTONFORDROPOFF);
	motor[armpickupmotor2] = (BUTTONFORDROPOFF);
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////
	  ////                                                   ////
	  ////      Add your robot specific tele-op code here.   ////
	  ////                                                   ////
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////

    // Insert code to have servos and motors respond to joystick and button values.

    // Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
    // You may be able to find "snippets" of code that are similar to the functions that you want to
    // perform.
  drive();
  armliftythingy();
  }
}
