#pragma config(Sensor, S1,     infra,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorB,          right,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,           tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"
#define DIVISOR 1.28
#define MARGIN 4
int sens;
bool tank = true;

void initializeRobot ()
{
	motor[left] = 0;
	motor[right] = 0;
}

void inf ()
{
	string s;
	sens = SensorValue[infra];
	sprintf(s, "Infared: %d",sens);
	nxtDisplayCenteredTextLine(2, s);
}

void drive ()
{
		getJoystickSettings(joystick);
		if (tank)
	{
		// translating joystick values from 128 to -127 to motor speeds
		float y1 = (float)(joystick.joy1_y1) / DIVISOR;
		float y2 = -(float)(joystick.joy1_y2) / DIVISOR;
		// wheels will be stopped when desired
		y1 = (abs(y1) - MARGIN < MARGIN) ? 0 : y1;
		y2 = (abs(y2) - MARGIN < MARGIN) ? 0 : y2;
		// sets motors
		motor[left] = y1;
		motor[right] = y2;
	}
}

task main()
{
	initializeRobot();

	while (true)
	{
	drive () ;
	}//end while
}//end task main
