#pragma config(Sensor, S1,     Infared,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorB,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int infsensdat;
void infra ()
{
	string s;
	infsensdat = SensorValue[Infared];
	sprintf(s, "Infrared: %d",infsensdat);
	nxtDisplayCenteredTextLine(2, s);
}

void drive ()
{

}

task main()
{
	while (true)
	{
		infra () ;
	}
}
