#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     _4ks2limit,     sensorTouch)
#pragma config(Sensor, S3,     _4ks3limit,     sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(Tetrix)
#include "JoystickDriver.c"

task main()
{

	int speed1, speed2;

//	TJoystick joystick;

	while(true)
	{

 		getJoystickSettings(joystick);

    speed1 = joystick.joy1_y1;
    speed2 = -joystick.joy1_x1;

		if(SensorValue(_4ks2limit) == 1)
		{
			speed1 =0;
	 		speed2 =0;
		}
		motor[motorD] = speed1;
		motor[motorE] = speed2;
	}
}

#if 0
//TJoystick joystick;

task main()
{
  while (true)
  {
    getJoystickSettings(joystick);
    //motor[motorD] = joystick.y1Pos;
    //motor[motorE] = joystick.y2Pos;
  }
}
#endif
