#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     _4ks2limit,     sensorTouch)
#pragma config(Sensor, S3,     _4ks3limit,     sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(Tetrix)
#include "JoystickDriver.c"

task main()
{

	int speed;

	speed=100;



TJoystick joystick;

	while(true)
	{

 getJoystickSettings(joystick);

    motor[motorD] = joystick.joy1_y1;
    motor[motorE] = joystick.joy1_x1;

		if(SensorValue(_4ks2limit) == 1)
		{motor[motorD] =0;
	 		motor[motorE] =0;
		}
	}
}

#if 0
//TJoystick joystick;

task main()
{
  while (true)
  {
    getJoystickSettings(joystick);
    //motor[motorD] = joystick.y1Pos;
    //motor[motorE] = joystick.y2Pos;
  }
}
#endif
