#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(Tetrix)

task main()
{

int speed;

speed=-100;

while (speed <=100)
{
  motor[motorD] = speed;
  speed = speed +10;
  wait1Msec(1000);
}

/*
  motor[motorE] = 100;
  wait1Msec(1000);

  motor[motorD] = 10;
  motor[motorE] = -50;
  wait1Msec(1000);

  PlaySound(soundBeepBeep);

  motor[motorD] = 60;
  motor[motorE] = -30;
  wait1Msec(1000);

  motor[motorD] = 500;
  motor[motorE] = 35;
  wait1Msec(1000);
  */

}
