#pragma config(Sensor, S1,     ZBoson,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          Bird,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          Cat,           tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"
#define DIVISOR 1.28
#define MARGIN 4
int infsensdat;
bool tank = true;

void infra ()
{
	string s;
	infsensdat = SensorValue[ZBoson];
	sprintf(s, "infared: %d",infsensdat);
	nxtDisplayCenteredTextLine(2, s);
}

void drive ()
{
		getJoystickSettings(joystick);
		if (tank)
	{
		// translating joystick values from 128 to -127 to motor speeds
		float y1 = (float)(joystick.joy1_y1) / DIVISOR;
		float y2 = -(float)(joystick.joy1_y2) / DIVISOR;
		// wheels will be stopped when desired
		y1 = (abs(y1) - MARGIN < MARGIN) ? 0 : y1;
		y2 = (abs(y2) - MARGIN < MARGIN) ? 0 : y2;
		// sets motors
		motor[Bird] = y1;
		motor[Cat] = y2;
	}
}

task main()
{
	infra ();
	drive () ;

}
